# Generated by Django 5.0.6 on 2024-06-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petanddogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='correo',
            new_name='mail',
        ),
    ]
