# Generated by Django 5.0.6 on 2024-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petanddogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='confContraseña',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
